# ##################### #
# # TTT Configuration # #
# ##################### #

# See http://ttt.badking.net/config-and-commands/convars#TOC-Karma
# for more detailed descriptions of certain config settings.

##################
# Round Settings #
##################

# The duration of the "preparation" period, before roles are assigned and the round fully starts.
preptime-seconds: 60

# The duration of rounds after the preparation period.
roundtime-seconds: 360

# The number of players required for a round to automtically enter its preparation period.
minimum-players: 3

# The maximum number of players permitted in a round (set to -1 for no limit).
maximum-players: 32

# Whether players may join rounds in-progress as spectators.
allow-join-as-spectator: true

##############################
# Traitor/Detective Settings #
##############################

# The ratio of traitors to innocents as a decimal.
traitor-pct: 0.25

# The ratio of detectives to other players.
detective-pct: 0.13

# The minimum number of players required for a detective to be assigned in a round.
# This will override the value of detective-pct if the minimum count is reached.
detective-min-players: 10

# The number of seconds required for the DNA scanner to charge (update).
# (Vanilla TTT uses 25 as default, but also displays the exact location rather than just the direction.)
scanner-charge-time: 7.5

# Maximum range in meters within which a DNA sample of the killer is planted on the corpse of the victim.
killer-dna-range: 10

# The time in seconds DNA samples last for when the killer is 0 meters from the victim.
# When the killer is further, the time will be decreased.
killer-dna-basetime: 100

##################
# Title Settings #
##################

# Whether TTT should send titles to players on round start and end.
# This will not do anything on Minecraft versions prior to 1.8.
send-titles: true

# Whether status titles (event.g. "You are a traitor!") should be sent as full-sized titles.
# If false (default), subtitles will be sent instead.
# Setting this to true may cause the title to obstruct the player's screen.
large-status-titles: false


# Whether status titles (event.g. "The traitors won!") should be sent as full-sized titles.
# If false (default), subtitles will be sent instead.
# Setting this to true may cause the title to obstruct the player's screen and additionally may
# cause the title to not fit on the screen for certain locales (such as de_DE).
large-victory-titles: false

###################
# Weapon Settings #
###################

# The item to use as a crowbar. This should be a raw Material enum value.
# See here for all valid values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
crowbar-item: IRON_SWORD

# The item to use as a gun. This should be a raw Material enum value.
# See here for all valid values: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# The default value, IRON_BARDING, represents iron horse armor.
gun-item: IRON_BARDING

# The amount of damage (in half-hearts) each hit with a crowbar should do.
crowbar-damage: 3

# Whether ammunition is required to use guns.
require-ammo-for-guns: true

# The number of arrows given to players on round start.
initial-ammo: 40

##################
# Karma Settings #
##################

# When strict is off, the damage penalty is very low when people stay above 800.
# However, beyond this limit it will follow a more parabolic curve, dropping more severely the lower the player's karma.
karma-strict: true

# The initial karma assigned to players. This will be clamped to karma-max.
karma-starting: 1000

# The maximum karma a player may hold at a given time.
# (After this is reached, the player will not receive karma until they go below it again.)
karma-max: 1000

# The ratio used in the formula used to determine the karma penalty for damaging an ally (0-1).
karma-ratio: 0.001

# From the official TTT documentation:
#
# All karma penalties are based on damage dealt. The kill penalty is just an extra amount of "damage" dealt
# when you kill someone. So if this was 100, and you headshot someone with a rifle, it would penalise you as
# if you dealt 200 damage.
karma-kill-penalty: 15

# The amount of karma allocated to each player on round end.
karma-round-increment: 5

# The amount of karma allocated on round end to each player who avoided friendly fire.
karma-clean-bonus: 30

# From the official TTT documentation:
#
# When a player's Karma is above the starting level (meaning the karma max has been configured to be higher than
# that), all his karma increases will be reduced based on how far his karma is above that starting level. So it
# goes up slower the higher it is.
karma-clean-half: 0.25

# The ratio used in the formula used to determine the karma reward to innocents for damaging a traitor (0-1).
karma-traitordmg-ratio: 0.0003

# The amount of karma given to an innocent upon killing a traitor.
# (This will be scaled by traitordmg-ratio and the victim's karma.)
karma-traitorkill-bonus: 40

# Players will be kicked from the round once they reach or go under this karma level. (Set to -1 for no autokick.)
karma-low-autokick: 450

# Whether players should be temporarily or permanently banned instead of kicked.
karma-low-ban: false

# The duration in minutes players will be banned for upon falling below the threshold. (Set to -1 for a permanent ban.)
# Note: changing this will not retroactively apply to previously issued bans.
karma-low-ban-minutes: 60

# Whether karma will persist through restarts and disconnects.
# If false, karma will reset when the plugin is reloaded and when players leave the server.
karma-persist: true

# Whether damage is scaled based on karma. At lower karma values, players will do less damage.
karma-damage-reduction: true

# Whether karma changes less than 1 should be rounded up.
karma-round-to-one: true

# Whether karma changes should be logged to the console. Note that this will typically cause massive log spam.
karma-debug: false

###################
# Plugin Settings #
###################

# Whether potentially unnecessary information should be logged.
verbose-logging: true

# The default locale used by the plugin.
# TTT will attempt to send messages to players in their respective locale, but will fall back to this if a message
# is not available in a locale. It will also be used for console messages.
locale: en_US

# Whether the plugin should update itself (highly recommended).
enable-auto-update: true

# Whether the plugin is allowed to submit anonymous usage information to MCStats.
enable-metrics: true
