name: TTT
version: 0.8.0-SNAPSHOT
main: net.caseif.ttt.TTTCore
author: Maxim Roncacé
website: http://dev.bukkit.org/bukkit-plugins/ttt
description: A Bukkit minigame based off the Garry's Mod gamemode Trouble In Terrorist Town.
softdepend: [Steel]

commands:
  ttt:
    description: The plugin's primary command.
    usage: /ttt [subcommand]
    # all below keys are useless, but are there for reference
    # arena-related commands
    import:
      description: Imports a TTT map from a specified folder in the server's root directory.
      usage: /ttt import [folder name]
    carena:
      description: Creates a new arena for use with TTT at the sender's or a specified location.
      usage: /ttt carena [arena name] {[x] [y] [z] [world]}
    rarena:
      description: Removes the given arena from TTT's registry.
      usage: /ttt rarena [arena name]
    addspawn:
      description: Adds the sender's or a specified location as a spawn to a specified arena.
      usage: /ttt addspawn [arena name] {[x] [y] [z]}
    removespawn:
      description: Removes the sender's or a specified location or an index as a spawn from the specified arena.
      usage: /ttt removespawn [arena name] {index}|{[x] [y] [z]}
    join:
      description: Adds player to a specified game of TTT.
      usage: /ttt join [map name]
    leave:
      description: Removes player from their current round.
      usage: /ttt leave
    # administrative commands
    prepare:
      description: Forces a round to enter its preparation stage.
      usage: /ttt prepare [arena name] {preparation time}
    start:
      description: Forces a round to enter its playing stage.
      usage: /ttt start [arena name] {playing time}
    end:
      description: Forces a round to end.
      usage: /ttt end [arena name] {victor (t/i)}
    kick:
      description: Kicks a player from their given TTT round.
      usage: /ttt kick [player name]
    ban:
      description: Bans a player from joining TTT rounds.
      usage: /ttt ban [player name] {minutes}
    pardon:
      description: Unbans a player from joining TTT rounds.
      usage: /ttt pardon [player name] {minutes}
    # general commands
    setexit:
      description: Sets the location to teleport players to upon round end.
      usage: /ttt setexit {true/false}
    help:
      description: Displays available commands to the sender.
      usage: /ttt help

permissions:
  ttt.*:
    description: Allows for full control and manipulation of the plugin.
    default: op
    children:
      ttt.admin.*: true
      ttt.arena.*: true
      ttt.lobby.*: true
      ttt.build.warn: true

  ttt.admin:
    description: Allows for full use of administrative commands.
    default: op
    children:
      ttt.admin.prepare: true
      ttt.admin.start: true
      ttt.admin.end: true
      ttt.admin.kick: true
      ttt.admin.ban: true
      ttt.setexit: true
      ttt.help: true
  ttt.admin.*:
    description: Allows for full use of administrative commands.
    children:
      ttt.admin: true
  ttt.admin.prepare:
    description: Allows player to force rounds to enter preparation stage.
    default: op
  ttt.admin.start:
    description: Allows player to force rounds to enter playing stage.
    default: op
  ttt.admin.end:
    description: Allows player to force rounds to end.
    default: op
  ttt.admin.kick:
    description: Allows player to kick players from their current TTT round.
    default: op
  ttt.admin.ban:
    description: Allows player to ban and unban players from joining TTT rounds.
    default: op

  ttt.arena:
    description: Grants all permissions beginning with ttt.arena.
    default: op
    children:
      ttt.arena.import: true
      ttt.arena.create: true
      ttt.arena.addspawn: true
      ttt.arena.removespawn: true
      ttt.arena.join: true
      ttt.arena.leave: true
  ttt.arena.*:
    description: Grants all permissions beginning with ttt.arena.
    children:
      ttt.arena: true
  ttt.arena.import:
    description: Allows player to import worlds into the plugin.
    default: op
  ttt.arena.create:
    description: Allows player to create arenas for use with the plugin.
    default: op
  ttt.arena.remove:
      description: Allows player to remove arenas from the plugin's registry.
      default: op
  ttt.arena.addspawn:
    description: Allows player to add spawns to an arena.
    default: op
  ttt.arena.removespawn:
    description: Allows player to remove spawns from an arena.
    default: op
  ttt.arena.join:
    description: Allows player to join TTT rounds.
    default: true
  ttt.arena.leave:
    description: Allows player to leave TTT rounds.
    default: true

  ttt.setexit:
    description: Sets the spawn upon round exit to the sender's current location.
    default: op

  ttt.help:
    description: Allows use of /ttt help.
    default: true

  ttt.lobby:
    description: Allows for full usage and manipulation of lobby signs.
    default: op
    children:
      ttt.lobby.create: true
      ttt.lobby.destroy: true
      ttt.lobby.use: true
  ttt.lobby.*:
    description: Allows for full usage and manipulation of lobby signs.
    children:
      ttt.lobby: true
  ttt.lobby.create:
    description: Allows creation of lobby signs.
    default: op
  ttt.lobby.destroy:
    description: Allows destruction of lobby signs.
    default: op
  ttt.lobby.use:
    description: Allows use of lobby signs.
    default: true

  ttt.build.warn:
    description: Players with this node will be notified of persistent issues with the plugin on join or command.
    default: op

  # deprecated nodes
  ttt.import:
    description: Allows player to import worlds into the plugin. (deprecated)
    default: false
    children:
      ttt.arena.import: true
  ttt.join:
    description: Allows player to join TTT rounds. (deprecated)
    default: false
    children:
      ttt.arena.join: true
  ttt.quit:
    description: Allows player to leave TTT rounds. (deprecated)
    default: false
    children:
      ttt.arena.leave: true
  ttt.setspawn:
    description: Sets the spawn upon round exit to the sender's current location. (deprecated)
    default: false
    children:
      ttt.setexit: true
