# ########################################### #
# # Trouble In Terrorist Town Configuration # #
# ########################################### #

#How long should rounds last for (in seconds)?
time-limit: 360

#How long should the plugin wait before starting a new round once enough players have joined?
setup-time: 90

#How many players are required to start a round?
minimum-players: 3

#What should the ratio of traitors to innocents be (as a decimal)?
traitor-ratio: 0.2

#How much damage should crowbars do at full karma? (How many half-hearts?)
crowbar-damage: 4
  
#Should guns be functional outside of arenas?
guns-outside-arenas: false

#Should ammunition (arrows) be required to use guns?
require-ammo-for-guns: true

#What should the ratio be for detectives to other players?
detective-ratio: 0.15

#If at least this many players are in a game, there is guaranteed to be a detective.
minimum-players-for-detective: 5

#Should potentially unnecessary information be logged?
verbose-logging: true

#Should the plugin allow auto-updating?
enable-auto-update: true

#Allow me to collect anonymous usage imformation (pretty please)?
enable-metrics: true

#What language would you like to use? If language is undefined, this will default to enUS)
localization: enUS

#Don't touch this. Please.
config-version: 0.3.0.22